# Generated by Django 4.0.5 on 2022-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Nacimiento', models.DateField(verbose_name='Nacimiento')),
                ('Edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('Trabajo', models.CharField(max_length=20, verbose_name='Trabajo')),
            ],
        ),
    ]
